### ISSUE TITLE
No se nos ocurre como ponerlo para que no quede de esta manera la funcion

### ISSUE THREAD

**Issue by luciaCalabrese** [CAMPUSCAMARAFP2021/Antonio-lu#1]
Buenas tardes, 
no se nos ocurre como mejorar esa parte del codigo,
al mismo tiempo quise poner 2 funciones que devuelvan tanto los ids de las pelis como una funcion que devuelva los ids de los generos

Gracias!
Lucia

**Comment by luciaCalabrese** [comment]
attachGenres() {

        this.getGenres().then(res => {
            const peliculas = res.genres;
            peliculas.forEach(generos => {
                const idGen = generos.id

                this.getMovies().then(res => {
                    const peliculas = res.results;
                    peliculas.forEach(pelis => {
                        const idPelis = pelis.genre_ids[0]
                        if (idGen === idPelis) {
                            console.log(pelis.title)
                            console.log(generos.name)
                        }
                    })
                })
            })
        })

    }

**Comment by davidpestana** [comment]
Hola @luciaCalabrese @Antoniooo266 piensa que la funcion asincrona nunca te devolvera datos ... te devolvera la promesa de los mismos... entonces vamos a ver un ejemplo de como incluir los nombres de los generos a las peliculas.

```
const getMoviesWithGenres = async () => {
      // espero por la lista de generos que usando destructuring lo saco directamente encadenando un then;
      const genres = await getGenres().then(({genres}) => genres);  
      // devuelvo la lista de pelis transformada llamando al metodo siguiente por cada peli.
      return getMovies().then(({results}) => results.map(movie => attachGenresToMovie(movie,genres)) 
} 


// este metodo cambia el array de ids de generos de un "movie" por un array de generos ( objeto )
const attachGenresToMovie = (movie, genres) => {
     movie.genres = movie.genres.map((genreId => genres.find(genre => genre.id === genreId);
     return movie;
}

```

**Comment by luciaCalabrese** [comment]
Buenas, gracias! 
He probado lo que nos has enviado y me dice que movie.genres no esta definido

**Comment by davidpestana** [comment]
claro, esta descontextualizado... es un ejemplo de como sería... tienes que ver dentro del modelo "movie" en que propiedad esta el array de genres y como viene codificado....     este ejemplo supone que genres sea un array de ids pero podria ser un array de objetos o estar modelado de otro modo... tienes que analizarlo y adaptarlo
