### ISSUE TITLE
Imprimir los datos en html

### ISSUE THREAD

**Issue by luciaCalabrese** [CAMPUSCAMARAFP2021/Antonio-lu#2]
Buenas tardes David,

no se me ocurre como hacer para imprimir los diferentes datos, provenientes de funciones/ promesas diferentes en una tabla,

Gracias

**Comment by davidpestana** [comment]
La promesa te promete que vendran los datos. ... entonces!!!

miPromesa.then((datos) => imprimolosdatos(datos)) 

o bien

const datos = await miPromesa; 
imprimoLosDatos(datos);

**Comment by luciaCalabrese** [comment]
Vale, muchas gracias
